#!/bin/bash

- name: loops in install packages ansible
  hosts: worker-node
  become: yes
  tasks:
  - name: loops install multiple packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - python3